# Generated by Django 6.0.3 on 2026-05-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('lunch_start_time', models.TimeField(blank=True, null=True)),
                ('lunch_end_time', models.TimeField(blank=True, null=True)),
                ('slot_duration', models.IntegerField(default=60)),
                ('week_holiday', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'barber_shop_settings',
            },
        ),
        migrations.CreateModel(
            name='EmergencyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField(unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emergency_holidays',
            },
        ),
    ]
