# Generated by Django 6.0.3 on 2026-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_barbershopsettings_emergencyholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyholiday',
            name='holiday_date',
        ),
        migrations.AddField(
            model_name='emergencyholiday',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyholiday',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyholiday',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyholiday',
            name='total_days',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
