# Generated by Django 6.0.3 on 2026-05-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_remove_emergencyholiday_holiday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyholiday',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
